steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rising-sector-405712/github.com/bamboo0079/kevin-awesome-project:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/rising-sector-405712/github.com/bamboo0079/kevin-awesome-project:$COMMIT_SHA', '.']  
